### ISSUE TITLE
don't commenting that we already know.

### ISSUE THREAD

**Issue by EXPITC** [FandiNur/ch2-day2#2]
https://github.com/FandiNur/ch2-day2/blob/93809c609868fb5a93ab86256b2ad907b5591178/assets/js/contact.js#L9-L20

commenting like this
`//function for checking the empty input and return alert if empty.`

**Comment by FandiNur** [comment]
Ok,I will check it. Sent from Mail for Windows From: INDRA T.CSent: 18 June 2022 15:15To: FandiNur/ch2-day2Cc: SubscribedSubject: [FandiNur/ch2-day2] don't commenting that we already know. (Issue #2) https://github.com/FandiNur/ch2-day2/blob/93809c609868fb5a93ab86256b2ad907b5591178/assets/js/contact.js#L9-L20comment like this//function for checking the empty input and return alert if empty.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
